function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // Char
	global.__objectDepths[1] = 0; // goggogogogogoo
	global.__objectDepths[2] = 0; // Play
	global.__objectDepths[3] = 0; // obj_credit
	global.__objectDepths[4] = 0; // Back_Cellect
	global.__objectDepths[5] = 0; // Back_stage1_ingame
	global.__objectDepths[6] = 0; // exitbutten_obj
	global.__objectDepths[7] = 0; // obj_back
	global.__objectDepths[8] = 0; // Load
	global.__objectDepths[9] = 0; // How_to_Next_
	global.__objectDepths[10] = 0; // Back_Menu
	global.__objectDepths[11] = 0; // warn_play
	global.__objectDepths[12] = 0; // Portal_obj
	global.__objectDepths[13] = 0; // lazer_obj
	global.__objectDepths[14] = 0; // lazer2_obj
	global.__objectDepths[15] = 0; // lazer3
	global.__objectDepths[16] = 0; // lazer4
	global.__objectDepths[17] = 0; // spike
	global.__objectDepths[18] = 0; // lazer01
	global.__objectDepths[19] = 0; // Lazer2
	global.__objectDepths[20] = 0; // Lazer90_1
	global.__objectDepths[21] = 0; // Lazer90_2
	global.__objectDepths[22] = 0; // Block
	global.__objectDepths[23] = 0; // block_hamjung
	global.__objectDepths[24] = 0; // ele_obj
	global.__objectDepths[25] = 0; // blo_hamjung_obj
	global.__objectDepths[26] = 0; // blo_hamjung_nosign
	global.__objectDepths[27] = 0; // Gravity_up
	global.__objectDepths[28] = 0; // Gravity_down
	global.__objectDepths[29] = 0; // Gravity_Right
	global.__objectDepths[30] = 0; // Gravity_left
	global.__objectDepths[31] = 0; // Saw_leftright_
	global.__objectDepths[32] = 0; // sawpoint_right_
	global.__objectDepths[33] = 0; // sawpoint_left_
	global.__objectDepths[34] = 0; // Saw_updown_
	global.__objectDepths[35] = 0; // sawpoint_down_
	global.__objectDepths[36] = 0; // sawpoint_up_
	global.__objectDepths[37] = 0; // s_lock
	global.__objectDepths[38] = 0; // s1_1
	global.__objectDepths[39] = 0; // s1_2
	global.__objectDepths[40] = 0; // s1_3
	global.__objectDepths[41] = 0; // s1_4
	global.__objectDepths[42] = 0; // s1_5
	global.__objectDepths[43] = 0; // s1_6
	global.__objectDepths[44] = 0; // s1_7
	global.__objectDepths[45] = 0; // s1_8
	global.__objectDepths[46] = 0; // s1_9
	global.__objectDepths[47] = 0; // s1_10
	global.__objectDepths[48] = 0; // St1_select
	global.__objectDepths[49] = 0; // stage1_game
	global.__objectDepths[50] = 0; // s2_1
	global.__objectDepths[51] = 0; // s2_2
	global.__objectDepths[52] = 0; // s2_3
	global.__objectDepths[53] = 0; // s2_4
	global.__objectDepths[54] = 0; // s2_5
	global.__objectDepths[55] = 0; // s2_big1
	global.__objectDepths[56] = 0; // stage2_game
	global.__objectDepths[57] = 0; // st2_select
	global.__objectDepths[58] = 0; // s3_1
	global.__objectDepths[59] = 0; // s3_2
	global.__objectDepths[60] = 0; // s3_3
	global.__objectDepths[61] = 0; // s3_4
	global.__objectDepths[62] = 0; // s3_5
	global.__objectDepths[63] = 0; // s3_6
	global.__objectDepths[64] = 0; // s3_7
	global.__objectDepths[65] = 0; // s3_8
	global.__objectDepths[66] = 0; // s3_9
	global.__objectDepths[67] = 0; // s3_10
	global.__objectDepths[68] = 0; // stage3_game
	global.__objectDepths[69] = 0; // st3_select
	global.__objectDepths[70] = 0; // s4_1
	global.__objectDepths[71] = 0; // s4_2
	global.__objectDepths[72] = 0; // s4_3
	global.__objectDepths[73] = 0; // s4_4
	global.__objectDepths[74] = 0; // s4_5
	global.__objectDepths[75] = 0; // s4_6
	global.__objectDepths[76] = 0; // s4_7
	global.__objectDepths[77] = 0; // s4_8
	global.__objectDepths[78] = 0; // st4_select
	global.__objectDepths[79] = 0; // st4_game
	global.__objectDepths[80] = 0; // restart_sys
	global.__objectDepths[81] = 0; // sys_cerser
	global.__objectDepths[82] = 0; // sys_start
	global.__objectDepths[83] = 0; // sys_room_draw
	global.__objectDepths[84] = 0; // Save_sys
	global.__objectDepths[85] = 0; // savepoint_1
	global.__objectDepths[86] = 0; // savepoint_2
	global.__objectDepths[87] = 0; // savepoint_3
	global.__objectDepths[88] = 0; // savepoint_4
	global.__objectDepths[89] = 0; // savepoint_5
	global.__objectDepths[90] = 0; // Back_Select4
	global.__objectDepths[91] = 0; // Back_Select3
	global.__objectDepths[92] = 0; // Back_Select2
	global.__objectDepths[93] = 0; // Back_Select1
	global.__objectDepths[94] = 0; // MainMenu_Select_BGM
	global.__objectDepths[95] = 0; // Stage4_BGM_sys
	global.__objectDepths[96] = 0; // Stage3_BGM_sys
	global.__objectDepths[97] = 0; // Stage2_BGM_sys
	global.__objectDepths[98] = 0; // Stage1_BGM_sys
	global.__objectDepths[99] = 0; // credit_BGM
	global.__objectDepths[100] = 0; // cheat
	global.__objectDepths[101] = 0; // nextroom
	global.__objectDepths[102] = 0; // select_left
	global.__objectDepths[103] = 0; // warndumm
	global.__objectDepths[104] = 0; // sys_pause
	global.__objectDepths[105] = 0; // sys_select
	global.__objectDepths[106] = 0; // Mentlegen_url
	global.__objectDepths[107] = 0; // Daniel_url
	global.__objectDepths[108] = 0; // FRdumm
	global.__objectDepths[109] = 0; // RFSdumm
	global.__objectDepths[110] = 0; // HTPdumm
	global.__objectDepths[111] = 0; // select_right


	global.__objectNames[0] = "Char";
	global.__objectNames[1] = "goggogogogogoo";
	global.__objectNames[2] = "Play";
	global.__objectNames[3] = "obj_credit";
	global.__objectNames[4] = "Back_Cellect";
	global.__objectNames[5] = "Back_stage1_ingame";
	global.__objectNames[6] = "exitbutten_obj";
	global.__objectNames[7] = "obj_back";
	global.__objectNames[8] = "Load";
	global.__objectNames[9] = "How_to_Next_";
	global.__objectNames[10] = "Back_Menu";
	global.__objectNames[11] = "warn_play";
	global.__objectNames[12] = "Portal_obj";
	global.__objectNames[13] = "lazer_obj";
	global.__objectNames[14] = "lazer2_obj";
	global.__objectNames[15] = "lazer3";
	global.__objectNames[16] = "lazer4";
	global.__objectNames[17] = "spike";
	global.__objectNames[18] = "lazer01";
	global.__objectNames[19] = "Lazer2";
	global.__objectNames[20] = "Lazer90_1";
	global.__objectNames[21] = "Lazer90_2";
	global.__objectNames[22] = "Block";
	global.__objectNames[23] = "block_hamjung";
	global.__objectNames[24] = "ele_obj";
	global.__objectNames[25] = "blo_hamjung_obj";
	global.__objectNames[26] = "blo_hamjung_nosign";
	global.__objectNames[27] = "Gravity_up";
	global.__objectNames[28] = "Gravity_down";
	global.__objectNames[29] = "Gravity_Right";
	global.__objectNames[30] = "Gravity_left";
	global.__objectNames[31] = "Saw_leftright_";
	global.__objectNames[32] = "sawpoint_right_";
	global.__objectNames[33] = "sawpoint_left_";
	global.__objectNames[34] = "Saw_updown_";
	global.__objectNames[35] = "sawpoint_down_";
	global.__objectNames[36] = "sawpoint_up_";
	global.__objectNames[37] = "s_lock";
	global.__objectNames[38] = "s1_1";
	global.__objectNames[39] = "s1_2";
	global.__objectNames[40] = "s1_3";
	global.__objectNames[41] = "s1_4";
	global.__objectNames[42] = "s1_5";
	global.__objectNames[43] = "s1_6";
	global.__objectNames[44] = "s1_7";
	global.__objectNames[45] = "s1_8";
	global.__objectNames[46] = "s1_9";
	global.__objectNames[47] = "s1_10";
	global.__objectNames[48] = "St1_select";
	global.__objectNames[49] = "stage1_game";
	global.__objectNames[50] = "s2_1";
	global.__objectNames[51] = "s2_2";
	global.__objectNames[52] = "s2_3";
	global.__objectNames[53] = "s2_4";
	global.__objectNames[54] = "s2_5";
	global.__objectNames[55] = "s2_big1";
	global.__objectNames[56] = "stage2_game";
	global.__objectNames[57] = "st2_select";
	global.__objectNames[58] = "s3_1";
	global.__objectNames[59] = "s3_2";
	global.__objectNames[60] = "s3_3";
	global.__objectNames[61] = "s3_4";
	global.__objectNames[62] = "s3_5";
	global.__objectNames[63] = "s3_6";
	global.__objectNames[64] = "s3_7";
	global.__objectNames[65] = "s3_8";
	global.__objectNames[66] = "s3_9";
	global.__objectNames[67] = "s3_10";
	global.__objectNames[68] = "stage3_game";
	global.__objectNames[69] = "st3_select";
	global.__objectNames[70] = "s4_1";
	global.__objectNames[71] = "s4_2";
	global.__objectNames[72] = "s4_3";
	global.__objectNames[73] = "s4_4";
	global.__objectNames[74] = "s4_5";
	global.__objectNames[75] = "s4_6";
	global.__objectNames[76] = "s4_7";
	global.__objectNames[77] = "s4_8";
	global.__objectNames[78] = "st4_select";
	global.__objectNames[79] = "st4_game";
	global.__objectNames[80] = "restart_sys";
	global.__objectNames[81] = "sys_cerser";
	global.__objectNames[82] = "sys_start";
	global.__objectNames[83] = "sys_room_draw";
	global.__objectNames[84] = "Save_sys";
	global.__objectNames[85] = "savepoint_1";
	global.__objectNames[86] = "savepoint_2";
	global.__objectNames[87] = "savepoint_3";
	global.__objectNames[88] = "savepoint_4";
	global.__objectNames[89] = "savepoint_5";
	global.__objectNames[90] = "Back_Select4";
	global.__objectNames[91] = "Back_Select3";
	global.__objectNames[92] = "Back_Select2";
	global.__objectNames[93] = "Back_Select1";
	global.__objectNames[94] = "MainMenu_Select_BGM";
	global.__objectNames[95] = "Stage4_BGM_sys";
	global.__objectNames[96] = "Stage3_BGM_sys";
	global.__objectNames[97] = "Stage2_BGM_sys";
	global.__objectNames[98] = "Stage1_BGM_sys";
	global.__objectNames[99] = "credit_BGM";
	global.__objectNames[100] = "cheat";
	global.__objectNames[101] = "nextroom";
	global.__objectNames[102] = "select_left";
	global.__objectNames[103] = "warndumm";
	global.__objectNames[104] = "sys_pause";
	global.__objectNames[105] = "sys_select";
	global.__objectNames[106] = "Mentlegen_url";
	global.__objectNames[107] = "Daniel_url";
	global.__objectNames[108] = "FRdumm";
	global.__objectNames[109] = "RFSdumm";
	global.__objectNames[110] = "HTPdumm";
	global.__objectNames[111] = "select_right";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
